version: "3"

services: 
    app:
      build: .
      container_name: "app_consumer"
      ports: 
        - 8901:8901
      volumes:
        - .:/src/app
      networks:
        - rabbitmq_network

    mongodb_container:
      image: mongo:latest
      container_name: "mongo_consumer"
      ports:
        - 27017:27017
      volumes:
        - ./mongo:/data/db
      
networks:
  rabbitmq_network:
    external: true
